### PR TITLE
feat(BrowserDetection): Cast the version parameter to String in compareVersion

### PR DESCRIPTION
**Pull request by hristoterezov**

### CODE REVIEW

**Comment by bbaldino** [comment]
there is some other code (the original fix) that can be removed now, isn't there?

**Comment by hristoterezov** [comment]
@bbaldino Are you talking about https://github.com/jitsi/lib-jitsi-meet/pull/716?

**Comment by bbaldino** [comment]
> @bbaldino Are you talking about jitsi/lib-jitsi-meet#716?

Yup, sorry didn't see that one.

**Comment by bgrozev** [comment]
I would prefer to throw a descriptive error if the type is not a string or a number, but I'm also fine with it as it is.

**Pull request merged**
