### PR TITLE
Update Electron userAgent detection

### LINKED ISSUE #29: Electron detection crashes
Hi,

when using Jitsi Meet in [Ferdi 5.5](https://getferdi.com) - based on Electron - the function `_detectElectron` in `browser-detection/BrowserDetection.js` crashes.

`navigator.userAgent` for this app is:
```
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 Ferdi/5.5.0 (Electron 8.2.3)"
```

The match attempt done by `_detectElectron` doesn't work:

```javascript
userAgent.match(/Electron\/([\d.]+)/)
null
```

So the `[1]` array access fails with "Uncaught TypeError: Cannot read property '1' of null".

Jitsi Meet used to work with Ferdi 5.4.3, which I guess was based on an older Electron version.

Thanks,
Chris

### PR DESCRIPTION
**Pull request by zeha**
Fixes #29

### CODE REVIEW

**Comment by zeha** [comment]
@emcho @saghul could you review this, please?

**Comment by saghul** [comment]
ccan you please share an example of the old and the new UA strings?

**Comment by zeha** [comment]
> ccan you please share an example of the old and the new UA strings?

Sorry, I don't have the old UA anymore.

New UA was mentioned in the issue:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 Ferdi/5.5.0 (Electron 8.2.3)
```

**Comment by saghul** [comment]
I’m not seeing this problem with Jitsi Meet electron. Any chance you have customized the UA in your app?

**Comment by zeha** [comment]
As said, I'm using Ferdi.app, which just happens to be an Electron app. It still shouldn't crash :)

**Comment by DanielMcAssey** [comment]
I believe the newer Electron versions (10+) changed the format of the UA, its not seperated by a slash anymore. My PR #33 marks it as optional

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/js-utils/pull/33

**Pull request closed without merging**
