### PR TITLE
update rename index.js to index.ts

### PR DESCRIPTION
**Pull request by daxiondi**
Obviously, this file is the syntax of typescript, but it is strangely named with the. JS suffix. As a result, other projects have problems installing this dependency library, so I think it should be renamed

### CODE REVIEW

**Comment by daxiondi** [comment]
Because this file leads to dependency problems, look here [Update README.md Resolve installation failure](https://github.com/jitsi/lib-jitsi-meet/pull/1235)

**Comment by daxiondi** [comment]
@saghul

**Comment by daxiondi** [comment]
@saghul 22222

**Comment by saghul** [comment]
It's not typescript, it uses flow for type annotations.

**Comment by saghul** [comment]
I'm proposing we drop flow in this project here: https://github.com/jitsi/js-utils/pull/37

**Comment by daxiondi** [comment]
It has been solved in this [pr](https://github.com/jitsi/js-utils/pull/37)

**Pull request closed without merging**
