### PR TITLE
Prepare publish

### PR DESCRIPTION
**Pull request by saghul**
TODO:

- [x] move the GH action to jitsi/ when we're happy with it
- [x] set the NPM token for this repo

### CODE REVIEW

**Comment by daxiondi** [comment]
Thank you very much for listening to me，But I really want this contribution to be made by me

**Comment by saghul** [comment]
> But I really want this contribution to be made by me

Sorry, it took a few exchanges to figure out what you meant and by then I was already mid-way preparing this.

**Comment by daxiondi** [comment]
> Sorry, it took a few exchanges to figure out what you meant and by then I was already mid-way preparing this.

It doesn't matter. Maybe I didn't express it clearly enough, but can I merge this [PR](https://github.com/jitsi/lib-jitsi-meet/pull/1235) I especially want to contribute to jitsi

**Comment by hristoterezov** [comment]
@saghul I don't see how "Drop flow" and "Drop precommit hook" is related to the PR. Could you please explain?  If they are not, let's move them to another PR!

Otherwise it LGTM to me! Although I have no idea what the .yml is doing :) But I like the idea of autopublish to npm!

**Comment by saghul** [comment]
I just stumbled across the flow dependency while updating them, if you agree with dropping it, do you mind if I keep them in this PR?

**Comment by daxiondi** [comment]
This is really a wise decision.

**Comment by saghul** [comment]
@hristoterezov Thank you! Will do.

**Comment by daxiondi** [comment]
> @hristoterezov Thank you! Will do.

I'm glad your PR has been merged. If it's empty, can you help me to see if there are any problems with this [PR](https://github.com/jitsi/lib-jitsi-meet/pull/1235)

**Pull request merged**
