### PR TITLE
feat: add random utils and meeting name generator

### PR DESCRIPTION
**Pull request by virtuacoplenny**

### CODE REVIEW

**Comment by paweldomas** [comment]
Is this the exact same logic that we used to have in jitsi-meet ?

**Comment by paweldomas** [comment]
Wasn't there another set of words used in spot ? I think I liked it more for spot's purpose

**Comment by virtuacoplenny** [comment]
There was another set of words but I was explicitly told to copy/paste the jitsi-meet implementation. I was told the implementation of random meeting names in jitsi-meet has some math behind it to hit some threshold of possible meeting combinations.

**Comment by damencho** [comment]
There was one more set in jidesha when we were using google cloud transcribe to convert speech to text for a room, and there was a server side limitation of 500 words, so we were limiting the dictionary there, but this is already in the history and should not be used.

**Pull request merged**
